{{- if .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
