resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

persistence:
  size: 5Gi
  # standard = StorageClass di default minikube per test
  storageClass: standard

config:
  maxConnections: "50"
  innodbBufferPoolSize: "128M"
