{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing # IP pubblico

    alb.ingress.kubernetes.io/target-type: ip # usa le sub pubbliche create nella VPC

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:... --> ARN del certificato ACM in prod 

    nginx.ingress.kubernetes.io/limit-rps: "100"
    
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"

spec:
  ingressClassName: {{ .Values.ingress.className }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific # delega la semantica del path al controller
            backend:
              service:
                name: {{ include "app-backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
