{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }} # almeno 1 pod deve rimanere running prima di spegnere gli altri 

  selector:
    matchLabels:
      {{- include "app-backend.selectorLabels" . | nindent 6 }}
{{- end }}
