apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
