{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
    # con kube-prometheus-stack il default è release: prometheus.
    release: {{ .Values.metrics.serviceMonitor.prometheusRelease }}
spec:
  selector:
    matchLabels:
      {{- include "app-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
