apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | b64enc | quote }}
  MYSQL_DATABASE:      {{ .Values.auth.database     | b64enc | quote }}
  MYSQL_USER:          {{ .Values.auth.username      | b64enc | quote }}
  MYSQL_PASSWORD:      {{ .Values.auth.password      | b64enc | quote }}
