apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  clusterIP: None # non viene assegnato un IP virtuale ma DNS risolve agli IP del pod (es. mysql-0.mysql-headless)
  ports:
    - port: 3306
      targetPort: mysql
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
